### ISSUE TITLE
Why the inconsistency with Opaleye in ==., >., etc.?

### ISSUE THREAD

**Issue by tomjaguarpaw** [ocharles/rel8#13]
Opaleye uses a prefix `.` to disambiguate boolean operators, `.==`., `.>`, etc..  rel8 uses a postfix `.`, `==.`, `>.`.  Is there any particular reason for this?  It feels like it would be nice to keep these as close as possible.

**Comment by ocharles** [comment]
I like the symmetry you get when you use them with qualified imports:
Rel8.==. Rather than Rel8..==

I believe this is also what persistent an esqueleto do, so it was less of a
change to our code base.

**Comment by tomjaguarpaw** [comment]
OK, I consider this an Opaleye issue then.  Thanks.
