### ISSUE TITLE
Are Aggregates Applicatives, or even Functors?

### ISSUE THREAD

**Issue by tomjaguarpaw** [ocharles/rel8#16]
In Opaleye you can do

```haskell
average :: Aggregator (Column PGFloat8) (Column PGFloat8)
average = (/) <$> sum <*> countStar
```

which is pretty cool.  It seems that in rel8, however, `Aggregate`s are not even Functors, let alone Applicatives.  Is that right?  (And indeed they shouldn't be because if they were you could create `Aggregate`s that allow columns to escape their scope.)

**Comment by ocharles** [comment]
Right, they aren't currently. I'm not entirely happy with the `Aggregate` type, so I may reconsider it at some point.
