### ISSUE TITLE
Status of the library?

### ISSUE THREAD

**Issue by tommyengstrom** [ocharles/rel8#17]
I was looking though the library and it looks great. Hats off to you sir!

How come this is not on hackage/stackage? Are there some important issues lurking? If so, can I help in some way?

**Comment by ocharles** [comment]
Hi, thanks for the kind words!

> How come this is not on hackage/stackage? Are there some important issues lurking? If so, can I help in some way?

We are using it very heavily in production, and haven't hit any problems. However, I'm still not convinced I've reached a stable API. It is possible to do this without arrows entirely, and instead use tagged monads to indicate scope. There is a trade off here though, as the types get more complicated.

I think I will probably bite the bullet and release it as it currently is, though - as it's definitely useful in its current form.

Thanks for your interest, that also helps me motivate a release :smile:

**Comment by tommyengstrom** [comment]
Cool! Then I'll just go ahead and use it in production as well.

**Comment by ocharles** [comment]
Awesome, please let me know if you have any difficulties or encounter any bugs. More than happy to take questions here.

**Comment by noxecane** [comment]
hi, @ocharles .... what's the name of hackage-package?

**Comment by ocharles** [comment]
Hi, this is not on Hackage and I'm unsure if it ever will be. These days I encourage people to explore [Beam](http://travis.athougies.net/projects/beam.html) instead
