### ISSUE TITLE
Define Expr to be existential Column?

### ISSUE THREAD

**Issue by tomjaguarpaw** [ocharles/rel8#6]
What do you think of making `Expr` an existential column?  i.e.

    newtype Expr t = forall a. Expr (Column a)

This would mean that you need to delve less into the internals of Opaleye, although you would need a lot of `unsafeCoerceColumn`s around the place.

**Comment by ocharles** [comment]
Oh, that doesn't sound like a bad idea! I'll give that a try

**Comment by ocharles** [comment]
One problem is that you can't have existentials with newtypes, so I do end up boxing a bit more - but I don't think it's the end of the world.

**Comment by ocharles** [comment]
Had a play with it and it doesn't really change that much. I still have a bunch of stuff that works with PrimExpr's in the general definition of what it means to be a table:

```haskell
  -- | Witness the isomorphism between the expression's functor of primitive
  -- expressions, and the user friendly expression type. A default
  -- implementation is provided, assuming every field in @expr@ contains
  -- exactly one 'Expr'.
  expressions :: Iso' expr (RowF expr O.PrimExpr)
```

`RowF` is some representable functor containing PrimExpr's for each column in the record, and storing `O.Column` here requires wrapping it up in `Colimit` or something. It doesn't really buy much unfortunately. If what a `O.Column` is changes in the future, then I'll explore this more, but for now it's easier for me to work with untyped `PrimExpr`s.

**Comment by tomjaguarpaw** [comment]
You could just use `Column ()`.

**Comment by ocharles** [comment]
I had a look at that just now and it still doesn't really seem to make anything clearer. If `O.Column` ever does change though, I'll have plenty of pointers of things to change and will consider a different representation then.
