### ISSUE TITLE
Opaleye Internal changes

### ISSUE THREAD

**Issue by tomjaguarpaw** [ocharles/rel8#7]
I'm concerned that rel8 is going to break on some upcoming Opaleye internal changes.  In particular there are culprits like this:

https://github.com/ocharles/rel8/blob/b44cfabeb7413bdeaba123ec7fc872f61ec11e09/Rel8/Internal/Table.hs#L352

In 0.6 `ColumnMaker` is becoming a synonym of `Unpackspec`.  Then in the future `Unpackspec` is probably going to have a different implementation too.  The way of accessing  them that is most robust to changes is via `Opaleye.Internal.TableMaker.column` and `Opaleye.Internal.Unpackspec.unpackspecColumn`.  I can probably keep those around in the internal API indefinitely, and in fact they probably should be public.

One thing you could do is to make a version [`traversePrimExprs`](https://github.com/ocharles/rel8/blob/b44cfabeb7413bdeaba123ec7fc872f61ec11e09/Rel8/Internal/Table.hs#L234) that works with `ProductProfunctor` like this

```haskell
traversePrimExprsPP
  :: (ProductProfunctor p, Table expr haskell)
  => (p O.PrimExpr O.PrimExpr) -> p expr expr
```

and then use `traversePrimExprsPP (dimap Column unColumn column)` instead of `O.ColumnMaker (O.PackMap traversePrimExprs)`.

**Comment by tomjaguarpaw** [comment]
In fact to be even more robust you can use `def` instead of `Opaleye.Internal.TableMaker.column` and `Opaleye.Internal.Unpackspec.unpackspecColumn`.

**Comment by ocharles** [comment]
I'm unclear if you're suggestion is to add something extra to the public API, or something internal. Eitherway, I'm not too bothered about having to do some work behind the scenes when Opaleye's internals change.

**Comment by tomjaguarpaw** [comment]
>  I'm not too bothered about having to do some work behind the scenes when Opaleye's internals change.

OK, fair enough.
