### ISSUE TITLE
Check rel8 builds with candidate opaleye-0.6.0.0

### ISSUE THREAD

**Issue by tomjaguarpaw** [ocharles/rel8#8]
I have a candidate of opaleye-0.6.0.0.  If you fancy checking whether rel8 is compatible before I release it you can try building against this commit:

https://github.com/tomjaguarpaw/haskell-opaleye/commit/57b4118f17b5f4a723be4cea344e6fd1e650b2aa

If you find any build errors I can fix them before release, though you'll have to apply the suggestion in https://github.com/ocharles/rel8/issues/7 to get rel8 to build on 0.5.4.0 and HEAD at the same time.

**Comment by ocharles** [comment]
Thanks - the only change I had to make was that `ColumnMaker` has gone.
